version: "3.3"
services:

  redis:
    image: "redis:6.2"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - lfpo-network
    environment:
      - REDIS_PASSWORD=197197

  spring_db:
    image: postgres:11
    container_name: agileblog
    restart: always
    volumes:
      - ./extras/postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=agileblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - lfpo-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=youremail@example.com
      - PGADMIN_DEFAULT_PASSWORD=yourpassword
    ports:
      - 8081:80
    networks:
      - lfpo-network

  agile-blog:
    image: lfpo2005/agile-blog
    restart: always
    build: .
    working_dir: /agile-blog
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://spring_db:5432/agileblog
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8080:8080
    command: java -jar /agile-blog/app.jar
    depends_on:
      - spring_db
      - redis
    networks:
      - lfpo-network

networks:
  lfpo-network:
    driver: bridge
