version: "3.9"
services:

  spring_db:
    image: postgres:11
    container_name: agileblog
    restart: always
    volumes:
      - ./extras/postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=agileblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - lfpo-network

  agile-blog:
    image: lfpo2005/agile-blog
    restart: always
    build: .
    working_dir: /agile-blog
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://spring_db:5432/agileblog
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8080:8080
    command: java -jar /agile-blog/app.jar
    depends_on:
      - spring_db
    networks:
      - lfpo-network


networks:
  lfpo-network:
    driver: bridge