version: "3.3"
services:

  spring_db:
    image: postgres:11
    container_name: agileblog
    restart: always
    volumes:
      - ./extras/postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=agileblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - lfpo-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=youremail@example.com
      - PGADMIN_DEFAULT_PASSWORD=yourpassword
    ports:
      - 8081:80
    networks:
      - lfpo-network

  agile-blog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://spring_db:5432/agileblog
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8090:8080
    command: java -jar /app/app.jar
    depends_on:
      - spring_db
      - redis
    networks:
      - lfpo-network

#  agile-blog:
#    image: lfpo2005/agile-blog
#    restart: always
#    build: .
#    working_dir: /agile-blog
#    environment:
#      SPRING.DATASOURCE.URL: jdbc:postgresql://spring_db:5432/agileblog
#      SPRING.DATASOURCE.USERNAME: postgres
#      SPRING.DATASOURCE.PASSWORD: postgres
#    ports:
#      - 8080:8080
#    command: java -jar /agile-blog/app.jar
#    depends_on:
#      - spring_db
#      - redis
#    networks:
#      - lfpo-network

networks:
  lfpo-network:
    driver: bridge
