version: "3.3"
services:

  agile-blog-prod:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING.DATASOURCE.URL: jdbc:postgresql://spring_db_prod:5432/agileblog
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8090:8080
    command: java -jar /app/app.jar
    depends_on:
      - spring_db_prod

  agile-blog-preprod:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: preprod
      SPRING.DATASOURCE.URL: jdbc:postgresql://spring_db_preprod:5432/agileblog
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8091:8080
    command: java -jar /app/app.jar
    depends_on:
      - spring_db_preprod

  agile-blog-dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING.DATASOURCE.URL: jdbc:postgresql://spring_db_dev:5432/agileblog
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8092:8080
    command: java -jar /app/app.jar
    depends_on:
      - spring_db_dev

  spring_db:
    image: postgres:11
    container_name: agileblog
    restart: always
    volumes:
      - ./extras/postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=agileblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - lfpo-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=youremail@example.com
      - PGADMIN_DEFAULT_PASSWORD=yourpassword
    ports:
      - 8081:80
    networks:
      - lfpo-network

networks:
  lfpo-network:
    driver: bridge
