server:
#  port: 8080
#  forward-headers-strategy: native
#  servlet:
#    context-path: '/blog'

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/agileblog
    username: postgres
    password: postgres
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    connection-timeout: 20000
    minimum-idle: 200
    maximum-pool-size: 550
    idle-timeout: 10000
    pool-name: PoolHikari
    auto-commit: false
  dbcp2:
    pool-prepared-statements: true
    max-open-prepared-statements: 550
  transaction:
    rollback-on-commit-failure: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  mail:
    host: mocha6007.mochahost.com
    port: 465
    username: contato@metodologia-agil.com.br
    password: '@Clf197197'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: mocha6007.mochahost.com
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  auth:
    jwtSecret: t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWn
    jwtExpirationMs: 14400000