name: CI

on:
  push:
    branches: [main, preprod]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3.5.2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Get version
        id: get_version
        run: echo "::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          Username: ${{ secrets.USER_DOCKER }}
          Password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
            lfpo2005/agile-blog:${{ github.ref == 'refs/heads/main' && 'latest' || 'preprod' }}
            lfpo2005/agile-blog:${{ steps.get_version.outputs.VERSION }}
